# Generated by Django 2.1.5 on 2019-01-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.CharField(max_length=50, verbose_name='Ementa')),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefoene')),
                ('valor_hora_aula', models.FloatField()),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(verbose_name='Data de Termino')),
                ('hora_inicio', models.TimeField(verbose_name='Horario de Inicio')),
                ('hora_termino', models.TimeField(verbose_name='Horario de Termino')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='turma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
    ]
