# Generated by Django 2.1.5 on 2019-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190107_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
